### ISSUE TITLE
counter should be words 4,5 not 12,13

### ISSUE THREAD

**Issue by ericlagergren** [jedisct1/forro#1]
Forro rearranges the matrix and puts t_0 at word 4 and t_1 at word 5.

**Comment by ericlagergren** [comment]
Or, rather, you're incrementing the wrong words :)

**Comment by jedisct1** [comment]
Oh, good catch!

I must confess that I didn't test this at all; just wanted to see what performance we could expect from Forro. And... well... it's not that great.

**Comment by ericlagergren** [comment]
@jedisct1 how many cpb were you getting?

**Comment by iagora** [comment]
Hi! I am one of the authors of Forró, happy to see the interest. Yes, depending on the processor Forró is not great, unless you resort to manually unrolling two executions of Forró, but it depends on architecture, I've confirmed the unrolling works on an ARMv8 and a few Intel's that I had at hand, but AMD hates me. Without resorting to this trick Forró is faster only in constrained devices, where Chacha's independent quarterrounds can´t reign supreme (concurrently), because we indeed have fewer operations.

**Comment by iagora** [comment]
I have the manual unroll [here](https://github.com/murcoutinho/forro_cipher/tree/main), it goes by Xote, if you ever feel inclined on testing, in the paper we show the performance for both implementations in a few devices, but since it depends on microarchitecture I'm dwelling on a way to choose the implementation cleverly.
